Zondax/namadexer

.gitignore
Cargo.lock
Cargo.toml
Makefile
benches/get_block_bench.rs
benches/save_blocks_bench.rs
benches/utils.rs
src/database.rs

This includes:
- benchmark for saving blocks into database.
- benchmark for getting blocks from the database and their txs.
We are using criterion andthe provided test vectors which are also used for testing.
Criterion performs many iterations(configured here for 10 iterations) and on each iteration, we save/query all the blocks from the test vectors into/from the database.
There could be false positives, it would depend on the system loads at the moment benchmarks are executed and either the database is local or remote. but in general, It is an excellent way to measure changes that might come with regressions/improvements in performance.
It is possible to see a report via HTML, this report is located in `target/criterion/report/index.html`
if present, criterion will try to use gnuplot …

Add benchmarks

---

config/Settings.example.toml
docs/03-indexer.md
src/config.rs
src/indexer/mod.rs

closes #21 
We can now specify in the `Setting.toml` file if the tendermint url is http or https.

misc: specify in Settings.toml if http or https url for tendermint

---

src/database.rs

closes #20 
We also remove the `USING HASH` index method because even if it creates smaller index, doing INSERT cost more with this method. `btree` the default is faster in this case.

feat: create fk for tx_*

---

src/server/blocks.rs
src/server/mod.rs
tests/block_tests.rs

fix: serialize tx_hashes as hex for json response

---

src/database.rs
src/server/tx.rs
src/tables.rs

closes #32 
This PR add the tx info on gas for wrapped transaction. It will give the amount per gas unit fee, the token it is in and the gas limit.
The server API also reflect those info.

feat: gas information for wrapped tx

---

src/server/endpoints.rs
src/server/endpoints/block.rs
src/server/endpoints/transaction.rs
src/server/mod.rs

This re-organizes the endpoint implementation better, instead of being spread across the module file, separating concerns and functionality. This could come in handy when more endpoints would be added for example for dealing with accounts.

Organize endpoint implementations

---

src/database.rs
src/tables.rs

closes #34 
This add the previous wrapper tx id to all decrypted id in the transaction table.

feat: add wrapper tx id for decrypted transaction

---

src/database.rs
src/server/blocks.rs
src/server/endpoints/block.rs
src/server/tx.rs

closes #37
This PR had the tx_type info to the block answer and add wrapper_id info for decrypted tx.

feat: improvements api

---

src/database.rs

closes #59 
This PR add a proper look up for the `code` event attributes to determine if the transaction has been successful. We used to assume the order wouldn't changed but it was reported in issue #59 that it changes.

fix: do proper lookup for event keys for transaction status

---

docs/04-server.md
src/database.rs
src/indexer/mod.rs
src/lib.rs
src/queries.rs
src/server/endpoints/transaction.rs
src/server/mod.rs
src/server/tx.rs
src/utils.rs

This:
- Fixes error when querying transactions by hash
- improve docs for new endpoints
- use the Rust option type for types that are set only if transaction type is a Wrapper
- move query string construction to its module to improve readability

fix transaction by hash and other improvements

---

src/tables.rs
tests/save_block.rs

closes #79 
closes #82 
We remove the constraint on `vote_proposal_id` to avoid error and have a better syncing result.

fix: vote_proposal_id not a primary key

---

src/server/blocks.rs
src/server/tx.rs

Remove the legacy check that was used to avoid panics when retrieving data from block and tx tables.
current code will error if the requested column does not exist.for number of columns in table

Remove legacy check

---

src/database.rs
src/server/tx.rs

fix indexing of vote_proposal transactions

remove is default from vote_proposal

---

config/Settings.example.toml
docs/03-indexer.md

This is a clarification on how to fix the issue explained in #95.

Clarify users that a create_index field is needed in the Settings.toml file

---

src/database.rs
src/server/endpoints/block.rs

Improve the endpoint /last/block to accept parameters (e.g `/block/last?num=5&offset=5`)

feat: able to query the latest few blocks from /block/last

---

Makefile

change version to download the appropriate checksum (changed to v0.31.1 for the shielded-expedition network)

checksum for shielded-expedition is v0.31.1

---

src/database.rs

Fixes issue #104 where too many VALUES were given to the tx_bridge_pool table.

INSERT has more expressions than target columns (issue #104)

---

src/lib.rs

The MASP address for shielded assets has changed. New one is `tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah`.

misc: update masp address for shielded expedition

---

config/Settings.example.toml
docs/04-server.md

Added to the Setting.example.toml file and the doc the change for the database port. It is now configurable and should be added in the config file.

fix: update doc and setting example to add port value

---

src/config.rs

This adds:
- Adds a default value for the database.port field in DatabaseConfig
- Implements a test to validate Settings.example.toml against the Settings struct, ensuring that changes in the configuration code are consistently reflected in the example file used in documentation.

Add settings test

---

Cargo.lock
Cargo.toml
src/database.rs

We have an error when trying to get the data in some cases of bridge transactions. We will not try to decode it anymore to avoid raising the error and just save the encoded data.

Fix: 'Invalid Transaction data' error

---

src/database.rs
src/error.rs

we ignore failed transaction when we are trying to decode them in the annexe tables

fix: tx_bond error message for failing tx

---

src/database.rs

Some failed transactions have failed because they don't have data. So we don't try to get the data on failed transaction at all.

fix: the invalid tx error when trasnction has failed

---

Cargo.lock
Cargo.toml
config/Settings.example.toml
contrib/helm/indexer-values.yaml
contrib/helm/server-values.yaml
docs/03-indexer.md
docs/04-server.md
src/config.rs
src/lib.rs
src/telemetry.rs

This introduces a new _optional_ config option `log_format` which can be either `"pretty"` (the default) or `"json"`.
When using `log_format = "json"` the logs will look like this:
```
{"timestamp":"2024-02-15T23:55:08.209893Z","level":"INFO","fields":{"message":"Starting database connection"},"target":"indexer"}
{"timestamp":"2024-02-15T23:55:08.307973Z","level":"INFO","fields":{"message":"Creating tables"},"target":"indexer"}
{"timestamp":"2024-02-15T23:55:08.308131Z","level":"INFO","fields":{"message":"Creating tables if they don't exist"},"target":"namadexer::database","span":{"name":"create_tables"},"spans":[{"name":"create_tables"}]}
{"timestamp":"2024-02-15T23:55:08.413702Z","level":"INFO","fields":{"message":"Starting indexer"},"target":"indexer"} …
```

Add support for json logging.

---

src/database.rs
src/error.rs
src/server/tx.rs

There are several different places where `Error::InvalidTxData` can be produced; this adds a `String` value to it so that every place that results in this error can also provide a helpful explanation.

Add reason string to InvalidTxData error.

---

src/database.rs

The database insertion logging is very verbose, and makes it hard to see what the application is doing (particularly when syncing / catching up). This changes those from `info!` to `debug!` so we can have a cleaner log by default while still being able to access those insertion logs if desired.

Change database traces from info -> debug

---

Dockerfile

This allows the docker image to be configured via env variables instead of a config file. (When `INDEXER_CONFIG_PATH` is set, the application will only use the file and will not attempt to read its config from env vars.) This is useful for environments like Google Cloud Run where it is simpler to set env vars than to mount a file into the container.

Do not set INDEXER_CONFIG_PATH by default in Dockerfile

---

src/indexer/mod.rs

Added a temp solution for the timeout issue. This PR add a timeout of 30secs which will lead to the indexer to crash if it doesn't get an answer from the RPC-JSON.
This is temp until the https://github.com/informalsystems/tendermint-rs/pull/1380 is merged in lib.

fix: added a timeout 

---

src/bin/indexer.rs
src/database.rs
src/indexer/mod.rs
src/lib.rs

This adds `gauge` metrics for last height retrieved from RPC and saved to the database for easier monitoring.
Similar to the `tendermint_consensus_latest_block_height{chain_id}` metric in the node, these also provide `chain_name` as a label.
Example of what this adds to prometheus:
```
indexer_last_save_block_height{chain_name="shielded_expedition"} 80144
indexer_last_get_block_height{chain_name="shielded-expedition"} 80246
```

Add metrics for indexer_last_get_block_height and indexer_last_save_block_height

---

src/database.rs
src/server/endpoints.rs
src/server/endpoints/address.rs
src/server/mod.rs
src/server/tx.rs

This PR add an endpoint to collect all of the transactions related to an address.

feat: get transactions per addresses

---

src/database.rs
src/lib.rs
src/views.rs

This PR create views when the indexer is launched and the time we create the tables to facilitate visualizing an retrieving the data for all different type of tx (see tx_*).
The advantage of this approach is that it doesn't take any supplementary space and doesn't need migration while facilitating interaction with the database.

feat: added views for ALL the tx type

---

Cargo.lock
Cargo.toml
examples/generate.rs
src/database.rs
src/indexer/mod.rs
src/lib.rs
tests/save_block.rs

This moves the checksums to a global, The reason is that it is not going to change during program execution and is loaded during program start, this condition makes it a good fit for wrapping into a Once Cell that gets lazily initialized.

Feat/checksums once_cell

---

src/views.rs

closes #174 
Small changes on the views to accommodate some users. In brief, we have added txid in al the views and addedthe missing fields in `tx_transfert`.

fix: added txid to views; added key and shielded field in tx_transfert view;

---

src/database.rs
src/views.rs

The views tx_vote_proposal and tx_transfer took in all transactions regardless of status (failed/succeeded). Updated views to only use successful transactions, as in former version tables. Note: An alternate approach might be to make the views richer and include fail/success status in tables. For now this is a quick fix.
(I assume this may be an issue with the other views as well, but not familiar enough with the data to fix atm. I have validated the data from this particular fix against former databases and seen that it's better corresponding)

Update views tx_vote_proposal and tx_transfer

---

src/database.rs
src/tables.rs

This PR add 2 new columns to the transactions table : `code_type` that translate the code in a human readable string and `memo` which contains the memo data associated with the transaction.
To avoid issue when deploying this new feature the table is altered if needed. Only new indexed block data will have those new values saved. To have previous data a fully resync is needed.

feat: add code_type value and memo data for transactions

---

src/bin/indexer.rs
src/database.rs
src/lib.rs

This helps reduce some more of the redundant metrics as described in https://github.com/Zondax/namadexer/issues/195 and https://github.com/Zondax/namadexer/issues/198.
COMPATIBILITY NOTE: this also renames the `db_save_` metrics to use common prefixes `db_save_duration_`, `db_save_batch_size_`, etc. instead of putting the metric type at the end of the name.

metrics: unify the histograms for all batch sizes; record batch size as a separate histogram
